config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root("cats#index")
  resources :favourites, only: [:index, :new, :create]
  resources :images, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cats_controller.rb
require 'net/http'
require 'uri'
require 'json'

class CatsController < ApplicationController
  include GetCurrentTime
  include RequestToApi
  def index
    @time = get_time
    random_picture = request_to_api('https://api.thecatapi.com/v1/images/search', 'get', 0, 0)
    @url_image = random_picture[0]['url']
    @id_image = random_picture[0]['id']
  end
end

app/controllers/concerns/get_current_time.rb
module GetCurrentTime
  extend ActiveSupport::Concern
  def  get_time
    Time.now
  end
end

app/controllers/concerns/request_to_api.rb
module RequestToApi
  extend ActiveSupport::Concern

  def request_to_api(url, request_type, image_id, user_id)
    uri = URI.parse(url)
    header = {'Content-Type': 'application/json', 'x-api-key': ENV['X_API_KEY']}
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    if(request_type.eql?'get')
      request = Net::HTTP::Get.new(uri, header)
      response = http.request(request)
      JSON.parse(response.body)
    elsif(request_type.eql?'post')
      request = Net::HTTP::Post.new(uri, header)
      body = {'image_id': image_id, 'sub_id': user_id}
      request.body = body.to_json
      response = http.request(request)
      response.read_body
    end
  end
end

app/controllers/favourites_controller.rb
require 'net/http'
require 'uri'

class FavouritesController < ApplicationController
  include RequestToApi

  def index
    response_body = request_to_api('https://api.thecatapi.com/v1/favourites', 'get', 0, 0)

    @all_favourite_links = []

    response_body.each do |fav|
      @all_favourite_links << {fav_image_id: fav['image_id']}
    end

    delete_empty_hash(@all_favourite_links)
  end

  def delete_empty_hash(arr_links)
    arr_links.each{ |x| x.delete_if{|key, value| value.eql?nil}}
    arr_links.delete_if { |hash| hash.empty? }
  end

  def new

  end

  def create
    @adding_result = request_to_api('https://api.thecatapi.com/v1/favourites', 'post', params['q'], params['y'])
    render :new
  end
end

app/controllers/images_controller.rb
require 'net/http'
require 'uri'
require 'json'

class ImagesController < ApplicationController
  include RequestToApi
  def show
    response = request_to_api('https://api.thecatapi.com/v1/images/' + params['id'], 'get', 0, 0)
    change_pictures_url(response)
  end

  def change_pictures_url(respond_from_api)
    respond_to do |format|
      format.json do
        render json: {
            url: respond_from_api['url']
        }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cats/index.html.erb
<h1>This is the main page</h1>
<h3>Pleace make your choise</h3>
<h3>Near you can chose URL what are you need</h3>
<%= link_to 'Page with favourites pictures', favourites_path %>
<br>
<%= link_to 'Page with form for add new favourites picture', new_favourite_path %>
<h5>Current time <%=@time%></h5>
<img src='<%= @url_image %>' alt="picture" class="testimg"/>
<p>Your image id: <%= @id_image %></p>

app/views/favourites/index.html.erb
<h1>This page contains all your favourites pictures</h1>
<% @all_favourite_links.each do |favourite| %>
  <%= image_tag("https://www.wpfreeware.com/wp-content/uploads/2014/09/placeholder-images.jpg", class: 'image', image_id: favourite[:fav_image_id], width: "300", height: "300") %>
<% end %>

app/views/favourites/new.html.erb
<h1>On this page you can add your picture to favourites</h1>

<%= form_tag("/favourites", method: "post") do %>
  <%= label_tag(:q, "Image id: ") %>
  <%= text_field_tag(:q) %>
  <%= label_tag(:y, "User id: ") %>
  <%= text_field_tag(:y) %>
  <%= submit_tag("Add...") %>
<% end %>

<h2>Result of adding: <%= @adding_result %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catsclub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>